# Generated by Django 3.2.4 on 2023-10-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(db_column='idusu', primary_key=True, serialize=False)),
                ('nombreu', models.CharField(db_column='nombre', max_length=100)),
                ('apellidou', models.CharField(db_column='apellido', max_length=100)),
                ('correou', models.CharField(db_column='correo', max_length=100, unique=True)),
                ('contraseñau', models.CharField(db_column='contraseña', max_length=255)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
