# Generated by Django 3.2.4 on 2023-10-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_respuesta', models.IntegerField(db_column='idrespuesta', primary_key=True, serialize=False)),
                ('colore', models.CharField(db_column='color', max_length=100)),
                ('frecuenciacome', models.CharField(db_column='frecuenciacom', max_length=100)),
                ('alquiladoañoe', models.CharField(db_column='alquilado', max_length=100)),
                ('frecuenciaalquie', models.CharField(db_column='frecuenciaalqui', max_length=100)),
                ('factorese', models.CharField(db_column='factores', max_length=100)),
                ('metodopagoe', models.CharField(db_column='metodopag', max_length=100)),
                ('malexpe', models.CharField(db_column='malexperiencia', max_length=100)),
                ('dispositivoe', models.CharField(db_column='dispositivo', max_length=100)),
                ('recibirofe', models.CharField(db_column='recibiof', max_length=100)),
                ('asistenciae', models.CharField(db_column='asistencia', max_length=100)),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
    ]
